# Outlook

This section summarizes some of my teaching-related goals for the near future.

## Interactive course content with quarto

As I already mentioned in the [Methods Section](methodology.qmd#sec-multimedia), I would like to gradually switch the content and materials for all my courses quarto projects, which would allow me to generate presentations, PDFs and also HTML documents/websites if needed from the same markdown content. I have already done so for parts or all of my ongoing courses (e.g. [Advanced Neuroimaging](https://natalia-zaretskaya.github.io/advanced-neuroimaging/) course content can be viewed under this [link](https://natalia-zaretskaya.github.io/advanced-neuroimaging/)) The next big milestone will be converting the content of the lecture series "General Psychology I: Perception and Attention". This is a larger endavour, because I provide a lot of text together with the lecture slides so that students who do not visit the lecture regularly can still prepare for the exam. I will also integrate my python code, animations, videos and demonstrations directly into the lecture materials.

## Trying out new teaching techniques

Having read the teaching concept of another professor, I got inspiration to try out new pedagogical tricks. One thing I would really like to try is tolerating a long silence period after asking a question when nobody dares to answer immediately.

## New courses

### Doctoral

#### Planning, executing, analyzing and writing up an fMRI study

This course will be largely based on, and developed from, the ongoing course in the master's curriculum. Here is the tentative course syllabus for UGOnline.

::: {=latex}
\renewcommand{\arraystretch}{2}  % increase to 1.5x default spacing
:::

+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Content                                                        | This practice-oriented seminar provides an introduction into the modern methods of MRI-based neuroimaging for cognitive neuroscience. It will take course participants through all stages of a functional MRI study:                                                                                                                                                                                                                                                                                                                                      |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   planning and programming an experiment,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   acquiring the data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   data preprocessing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   data analysis and interpretation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | Course participants can choose between working on an experiment which is part of their doctoral thesis, or inventing a completely new experiment.                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | In addition to theoretical input, the course will have a strong practical component. Students will first present their projects/ideas in class. After this, the class will select the best project, which will be implemented into a computer program. Together with the lecturer we will conduct an fMRI experiment with one volunteer. The course participants will get access to a server, and each person will go through all stages of data preprocessing and analysis. Open science practices in the field of neuroimaging will also be introduced. |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Previous Knowledge Expected                                    | Basic knowledge of neuroimaging methods in cognitive neuroscience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Objective (Expected Results of Study and Acquired Competences) | After completing the course participants should be able to:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   understand the possibilities and limitations of functional MRI experiments                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   be able to plan and conduct fMRI experiments in practice                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | -   know and apply open science practices in the field of neuroimaging                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Languages of Instruction                                       | English                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Teaching and Learning Method (Transfer of Skills)              | Under the supervision of the course instructor, students will acquire knowledge by:                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | a) reading, understanding, and critically reviewing the newest scientific research literature related to the topic                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                | b) conducting a small fMRI project and interpreting its results                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Workload for students                                          | In-class oral presentations, experiment preparation (divided across class members), individually conducted data analysis, individual final essay                                                                                                                                                                                                                                                                                                                                                                                                          |
+----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[30,70\]"}

#### Journal club

Although doctoral students in psychology doctoral school are used to critically reading articles from their undergraduate studies (I heard from the colleague at the MedUni that it is the other way around for them), I think it is important to keep up the critical thinking skill, while at the same time being aware of the most recent literature. This course is not planned yet, this is my idea for the not-so-near future.

::: {=latex}
\renewcommand{\arraystretch}{2}  % increase to 1.5x default spacing
:::

+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Content                                                        | This seminar is intended to train doctoral students in critical thinking and scientific presentation skills, while learning about newest developements in the research field directly relevant for their theses work.                                                                                                                                                                                                                          |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                | Each course participant will chose a paper directly relevant for the topic of their PhD thesis and present it in class with a critical discussion of the paper's content. Course participants will be required to read the paper and ask at least one question to the speaker, submitting the questions beforehand. In each session in addition to the presenter/speaker, one other person will introduce the speaker and moderate discussion. |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Previous Knowledge Expected                                    | n/a                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Objective (Expected Results of Study and Acquired Competences) | After completing the course participants should be able to:                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                | -   critically assess scientific articles in their or related field                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                | -   present the content of a scientific article in a clear and understandable manner                                                                                                                                                                                                                                                                                                                                                           |
|                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                | -   be able to lead a scientific discussion                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Languages of Instruction                                       | English                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Teaching and Learning Method (Transfer of Skills)              | Under the supervision of the course instructor students will acquire knowledge by reading, understanding and critically reviewing newest scientific research literature related to the topic.                                                                                                                                                                                                                                                  |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Workload for students                                          | Workload for students: In-class oral presentations, weekly readings and questions, individual final essay.                                                                                                                                                                                                                                                                                                                                     |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[30,70\]"}
