# Philosophy

There are many important principles that I apply or try to apply in teaching. This section briefly summarized those ones that are particularly important for me.

## *“We work for* tomorrow*”*

The current slogan of the University of Graz perfectly matches my teaching goal of educating young professionals that are well equipped for the challenges of the modern world, such as big data and digitalization. To achieve this goal, I try to integrate newest trends and developments in research theory and practice into the curriculum. Students in my courses are up to date on the newest software and digital research tools, open science practices, statistics approaches, and, most importantly, on the most recent research findings. I also try to show them the relevance of the topics we cover for our everyday life and society. For example, when talking about the neural mechanisms of consciousness, we also discuss the potential consciousness of Artificial Intelligence and ethical issues associated with it. When talking about basic perceptual mechanisms I indicate how these principles are employed in advertisement.

## Research first

For me this term means much more than just integration of research into teaching activities. In my courses students practice different aspects of *being* researchers, with me acting as their senior colleague rather than a lecturer. I support students in pursuing their interests, while they can draw upon my knowledge and experience in solving specific research problems. In addition to receiving formal knowledge, I introduce the internal logic of research, accepted practices and unwritten rules. Although I would love to see every one of my student becoming a top-class researcher, it is clear to me that only a tiny fraction of them will become researchers at all. Nevertheless, I do not want to lower the bar, since I believe that knowing how research is done is important for every responsible citizen.

## Continuous self-improvement

### Didactics courses

Throughout my career I have always striven for improving my teaching skills. Already as a graduate student I completed a course on university teaching and didactics, and continued to visit structured courses ever since (a list of attended didactic courses is available in the [Appendix](appendix.qmd#sec-certificates)).

### Informal exchange

Apart from formal education, I get inspiration, insights and valuable ideas by exchanging experience with colleagues over lunch or coffee. Currently I exchange teaching experience with one-two colleagues from my group. I think it would be great to be able to share and get insights on teaching from other colleages of the department of psychology or even from other natural science faculty staff. A nice initiative could be regular (even if they are once per semester) lunch meetings. But I think fruitful exchange happens primarily with closer colleagues which I would also consider friends, so that there is no incentive to appear better than I am in teachign or to hide something embracing and to be able to openly admit my mistakes.

A useful experience is teaching a course together with another colleague. So far I did this with a more experienced colleague to learn from her. A useful experience can also be teaching with a junior colleague, so that they can learn from my experience. So far I only invited my doctoral students to participate in individual course days, but never to teach together. This could be something to try out in the future.

Most importantly, I regularly ask students who have participated in my courses in the past and then joined my lab in another capacity for input about what was useful and what could have been done better. Also students whom I never taught myself, but who joined my lab as interns, bachelor or master students can oftentimes provide valuable insights into the needs the students have in terms of course structure and content.

### Formal feedback

Every full course I held has undergone a final evaluation using the standard UGOnline questionnaire. At the University of Graz I subjected every course to the evaluation procedure voluntarily (course evaluations are available in the [Appendix](appendix.qmd#sec-evaluations)).

Considering course evaluations and student feedback are for me an important tool for self-improvement. I always consider feedback to previous courses when revising the course structure and format for the next semester. When doing so, I do not indiscriminately implement all student suggestions or try to address all critique (most of the time it is impossible), but critically weight out the comments against teaching goals, curriculum requirements and course format. For example, would not implement a students' wish for more upfront teaching for a seminar course if I already spend 50% of class time on it, because a seminar format implies active students contributions as well, and a teacher-centered class would defeat the whole purpose of the seminar. Once the evaluation is over, I usually respond to critique (if I don't forget to do so before the deadline set in UGOnline), and make the evaluation public. I hope that students take advantage of this information when considering whether to take the course or not in addition to, or, ideally, instead of using Studo.

Even though during the last class I always reserve time for anonymous UGOnline feedback, some students manage not to submit their comment nevertheless. This semester I implemented a new rule in my courses, requiring students to submit evaluation through UGOnline as a part of their coursework in order to be graded (theevaluation remains anonymous, but students need to submit a screenshot confirmation that they completed the evaluation). I am curious to see how it turns out.

### Inspirational teaching

When I teach I try to show students that I care about teaching quality. Many times students noted in their feedback that they see me as a competent, but also motivated and caring instructor. I think the fact that they see someone who truly cares about conveying the message and reachign the teaching goals serves as an additional motivator for students in studying for my courses.

## AI usage

Artificial intelligence can be used for almost any type of course work/course task these days, and it is almost impossible for a teacher to control AI usage without becoming overwhelmed. I found a recent study [@kosmyna2025]on GPT usage for writing conducted at MIT quite insightful, and I am planning to present the study and its results at the first session of every new course I start. I give advice on where to use and where not to use AI, and also report on my personal experience on usage of different AI tools. But ultimately I can't control whether AI has been used without disclosure, and I don't think anyone can.
